Models/ErrorViewModel.cs
namespace ASP.NETMVCSchool.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Student.cs
namespace ASP.NETMVCSchool.Models
{
    public class Student
    {
        public int Id { get; set; }
        public required string FirstName { get; set; }
        public required string LastName { get; set; }
        public DateTime DateOfBirth { get; set; }        
    }
}

Models/Subject.cs
namespace ASP.NETMVCSchool.Models
{
    public class Subject {
        public int Id { get; set; }
        public required string Name { get; set; }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using ASP.NETMVCSchool.Models;
using Microsoft.AspNetCore.Mvc;

namespace ASP.NETMVCSchool.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/StudentsController.cs
using ASP.NETMVCSchool.DTOs;
using ASP.NETMVCSchool.Services;
using Microsoft.AspNetCore.Mvc;

namespace ASP.NETMVCSchool.Controllers
{
    public class StudentsController : Controller
    {
        private StudentService _service;

        public StudentsController(StudentService service)
        {
            _service = service;
        }
        public IActionResult Index()
        {
            var allStudents = _service.GetAllStudents();
            return View(allStudents);
        }
        // akce Create pro zobrazení formuláře pro vytvoření nového studenta
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        // akce Create volaná formulářem pro vytvoření nového studenta
        [HttpPost]
        public IActionResult Create(StudentDTO student)
        {
            _service.CreateStudent(student);
            return RedirectToAction("Index");          
        }
        // akce Edit pro zobrazení detailu studenta
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var student = _service.GetStudentById(id);
            if (student == null) return NotFound();
            return View(student);
        }
        // akce Edit volaná formulářem pro úpravu studenta
        [HttpPost]
        public IActionResult Edit(int id, StudentDTO student)
        {
            _service.UpdateStudent(id, student);
            return RedirectToAction("Index");
        }
        // akce Delete pro smazání studenta
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var student = _service.GetStudentById(id);
            if (student == null)
            {
                return View("NotFound");
            }
            _service.DeleteStudent(id);
            return RedirectToAction("Index");
        }
    }
}

Controllers/SubjectsController.cs
using ASP.NETMVCSchool.DTOs;
using ASP.NETMVCSchool.Models;
using ASP.NETMVCSchool.Services;
using Microsoft.AspNetCore.Mvc;

namespace ASP.NETMVCSchool.Controllers
{
    public class SubjectsController : Controller
    {
        private SubjectsService _service;
        public SubjectsController(SubjectsService service)
        {
            _service = service;
        }
        public IActionResult Index()
        {
            var allSubjects = _service.GetAllSubjects();
            return View(allSubjects);
        }
        // akce Create pro zobrazení formuláře pro vytvoření nového předmětu
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        // akce Create volaná formulářem pro vytvoření nového předmětu
        [HttpPost]
        public IActionResult Create(SubjectDTO subjectDTO)
        {
            _service.CreateSubject(subjectDTO);
            return RedirectToAction("Index");
        }
        // akce Delete pro smazání předmětu
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var subject = _service.FindSubjectById(id);
            if (subject == null)
            {
                return View("NotFound");
            }
            _service.DeleteSubject(id);
            return RedirectToAction("Index");
        }
        // akce Edit pro zobrazení detailu předmětu
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var subject = _service.FindSubjectById(id);
            if (subject == null) return NotFound();
            return View(subject);
        }
        // akce Edit volaná formulářem pro úpravu předmětu
        [HttpPost]
        public IActionResult Edit(int id, SubjectDTO subjectDTO)
        {
            var existingSubject = _service.FindSubjectById(id);
            if (existingSubject == null) return NotFound();
            _service.UpdateSubject(id, subjectDTO);
            return RedirectToAction("Index");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP.NETMVCSchool</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP.NETMVCSchool.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP.NETMVCSchool</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subjects" asp-action="Index">Subjects</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ASP.NETMVCSchool - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Students/Create.cshtml
@using ASP.NETMVCSchool.DTOs

@model StudentDTO


<div>
    <h4>Create new student</h4>
    <form asp-action="Create">
        <div class="form-group">
            <label asp-for="FirstName" class="control-label"></label>
            <input asp-for="FirstName" class="form-control" type="text" />
        </div>
        <div class="form-group">
            <label asp-for="LastName" class="control-label"></label>
            <input asp-for="LastName" class="form-control" type="text" />
        </div>
        <div class="form-group">
            <label asp-for="DateOfBirth" class="control-label"></label>
            <input type="date" asp-for="DateOfBirth" class="form-control" />
        </div>
        <div>
            <input class="btn btn-success" type="submit" value="Create" />
        </div>
    </form>
</div>

Views/Students/Edit.cshtml
@using ASP.NETMVCSchool.DTOs

@model StudentDTO

<div>
    <h4>Edit student</h4>
    <form asp-action="Edit">
        <div class="form-group">
            <label asp-for="FirstName" class="control-label"></label>
            <input asp-for="@Model.FirstName" class="form-control" type="text" />
        </div>
        <div class="form-group">
            <label asp-for="LastName" class="control-label"></label>
            <input asp-for="@Model.LastName" class="form-control" type="text" />
        </div>
        <div class="form-group">
            <label asp-for="DateOfBirth" class="control-label"></label>
            <input type="date" asp-for="@Model.DateOfBirth" class="form-control" />
        </div>
        <div>
            <input class="btn btn-success" type="submit" value="Update" />
        </div>
    </form>
</div>

Views/Students/Index.cshtml
@using ASP.NETMVCSchool.DTOs
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model IEnumerable<StudentDTO>
<h1>List of all students</h1>
@foreach (var student in Model)
{
    <div class="border border-1 p-2">
        <h5>@student.FirstName @student.LastName</h5>
		<p>Id: @student.Id<p/>
        <p>Date of Birth: @student.DateOfBirth.ToShortDateString()</p>
        <a class="btn btn-warning" asp-action="Edit" asp-route-id="@student.Id">Edit</a>
        <form method="post">
			<button type="submit" class="btn btn-danger" asp-action="Delete" asp-route-id="@student.Id">Delete</button>
		</form>
    </div>
}
<hr />
<div>
    <a class="btn btn-success" asp-action="Create">Create</a>
</div>

Views/Subjects/Create.cshtml
@using ASP.NETMVCSchool.DTOs

@model SubjectDTO

<div>
    <h4>Create new subject</h4>
    <form asp-action="Create">
        <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" type="text" />
        </div>        
        <div>
            <input class="btn btn-success" type="submit" value="Create" />
        </div>
    </form>
</div>

Views/Subjects/Edit.cshtml
@using ASP.NETMVCSchool.DTOs

@model SubjectDTO

<div>
    <h4>Edit subject</h4>
    <form asp-action="Edit">
        <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="@Model.Name" class="form-control" type="text" />
        </div>        
        <div>
            <input class="btn btn-success" type="submit" value="Update" />
        </div>
    </form>
</div>

Views/Subjects/Index.cshtml
@using ASP.NETMVCSchool.DTOs

@model IEnumerable<SubjectDTO>

<h4>Subjects Index</h4>
@foreach (var subject in Model)
{
	<div class="border border-1 p-2">
		<h5>@subject.Name</h5>
		<p>Id: @subject.Id<p />
		<a class="btn btn-warning" asp-action="Edit" asp-route-id="@subject.Id">Edit</a>
		<form method="post">
			<button type="submit" class="btn btn-danger" asp-action="Delete" asp-route-id="@subject.Id">Delete</button>
		</form>
	</div>
}
<hr />
<div>
	<a class="btn btn-success" asp-action="Create">Create</a>
</div>